
[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  functionsPort = 5178
  targetPort = 5178