[build]
  base = "/"
  command = "npm install vite && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  functionsPort = 8888
  targetPort = 8888