[build]
  base = "/"
  command = "npm install && cd netlify && npm install && cd ../ && npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  functionsPort = 8888
  targetPort = 8888